"""empty message

Revision ID: 4824586be210
Revises: 736d0afaf521
Create Date: 2021-02-01 20:11:45.777579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4824586be210'
down_revision = '736d0afaf521'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('exam_question_exam_id_fkey', 'exam_question', type_='foreignkey')
    op.create_foreign_key(None, 'exam_question', 'exam', ['exam_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('mcq_in_question_exam_question_id_fkey', 'mcq_in_question', type_='foreignkey')
    op.create_foreign_key(None, 'mcq_in_question', 'exam_question', ['exam_question_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mcq_in_question', type_='foreignkey')
    op.create_foreign_key('mcq_in_question_exam_question_id_fkey', 'mcq_in_question', 'exam_question', ['exam_question_id'], ['id'])
    op.drop_constraint(None, 'exam_question', type_='foreignkey')
    op.create_foreign_key('exam_question_exam_id_fkey', 'exam_question', 'exam', ['exam_id'], ['id'])
    # ### end Alembic commands ###
