"""empty message

Revision ID: 78a9455c2b80
Revises: c75e51964a24
Create Date: 2021-01-31 11:24:32.497504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78a9455c2b80'
down_revision = 'c75e51964a24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'course')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('course', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
