"""empty message

Revision ID: 830522aad6c2
Revises: 
Create Date: 2021-02-01 19:30:44.139771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '830522aad6c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exam_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('question_no', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mcq_in_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_question_id', sa.Integer(), nullable=True),
    sa.Column('mcq_id', sa.Integer(), nullable=True),
    sa.Column('mcq_no', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exam_question_id'], ['exam_question.id'], ),
    sa.ForeignKeyConstraint(['mcq_id'], ['MCQ.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mcq_in_question')
    op.drop_table('exam_question')
    op.drop_table('exam')
    # ### end Alembic commands ###
