"""empty message

Revision ID: 9533c3593a91
Revises: 4824586be210
Create Date: 2021-02-04 05:59:48.056917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9533c3593a91'
down_revision = '4824586be210'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam', sa.Column('score', sa.Integer(), nullable=True))
    op.add_column('exam_question', sa.Column('ans_selected', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam_question', 'ans_selected')
    op.drop_column('exam', 'score')
    # ### end Alembic commands ###
