"""empty message

Revision ID: d5d997919d60
Revises: f560da101b08
Create Date: 2021-02-04 12:09:17.371452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5d997919d60'
down_revision = 'f560da101b08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_on', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_on')
    # ### end Alembic commands ###
